env:
  global:
    - CC_TEST_REPORTER_ID=1991acb633e90e7202a5d1fac9998f78b608f40147363199553cf70ecf5b2564
    - TESTSALT=86A96823-FD69-4556-8960-34887473750A
language: go
go:
  - "1.13.x"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -coverprofile c.out ./...
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
